### PR TITLE
#121 Validate text

### LINKED ISSUE #121: Profile screen
Requires authentication.

## Basic content:
- avatar
- username
- email

More features could be added up to the developer ideas.

## Future
In the future, this screen could be extended to include user activities such as:
- liked photos
- uploaded photos
- last comments
- bio

## Tasks: 

- [x] Show user data
- [x] Update avatar in Firebase
- [x] Adjust UI add information about edit for avatar
- [x] Update user name
- [x] Handle exception
- [x] Extract same statements from updateAvatar, updateName, fetchProfile in ProfileViewModel 
- [x] Add placeholder for loading
- [x] Validate text

### PR DESCRIPTION
**Pull request by Nataniel-Antosik**
https://github.com/intive/Picover/assets/57491794/6f35e787-9b66-427a-a09f-f130ac686447

### CODE REVIEW

File: app/src/main/kotlin/com/intive/picover/validators/TextValidator.kt [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+			return false
+		}
+
+		return true
+	}
+
+	class Builder(private val text: String) {
+		private var allowEmpty: Boolean = true
+		private var allowBlank: Boolean = true
+		private var maxLength: Int = 0
```
Comment (bartek977) [inline app/src/main/kotlin/com/intive/picover/validators/TextValidator.kt]: I wonder if wouldn't be better to make these properties nullable instead of default values, and then in function `isValidated()` check only conditions which are not null

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt [hunk 2]
```diff
@@ -199,23 +199,36 @@ fun ProfileScreen(viewModel: ProfileViewModel) {
...
+					modifier = Modifier
+						.fillMaxWidth(),
+					value = userName,
+					onValueChange = {
+						userName = it
+					},
+					isError = !viewModel.isNameValidated(userName),
+					label = { Text(stringResource(id = R.string.UserName)) },
+				)
+				if (!viewModel.isNameValidated(userName)) {
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt]: don't we have `supportingText` parameter for the material 3 textfield :D ? maybe this can be used, with error color, instead of additional Text()

**Review by marcinWisnia — CHANGES_REQUESTED** [review]

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt [hunk 3]
```diff
@@ -199,23 +199,36 @@ fun ProfileScreen(viewModel: ProfileViewModel) {
...
 					.padding(start = 20.dp, end = 20.dp, bottom = 42.dp)
 					.fillMaxWidth(),
-				value = userName,
-				onValueChange = {
-					userName = it
-				},
-				label = { Text(stringResource(id = R.string.UserName)) },
-			)
+			) {
+				TextField(
```
Comment (Nataniel-Antosik) [inline app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt:211]: Add character counter

Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt:211]: Done

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt (hunk 2 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt]: Done 😄

File: app/src/main/kotlin/com/intive/picover/validators/TextValidator.kt (hunk 1 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/validators/TextValidator.kt]: Done 😄

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt [hunk 4]
```diff
@@ -65,6 +66,14 @@ class ProfileViewModel @Inject constructor(
 		}
 	}
 
+	fun validatingName(text: String) =
+		TextValidator.Builder(text)
+			.allowEmpty(allow = false)
+			.allowBlank(allow = false)
+			.maxLength(length = 20)
```
Comment (bartek977) [inline app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: minor: I think parameters names are unnecessary as the function name is meaningful enough

File: app/src/main/kotlin/com/intive/picover/validators/ValidationStatus.kt [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+
+			is TooLongText -> {
+				return R.string.TextIsTooLong
+			}
+
+			else -> {
+				return R.string.TextIsValid
+			}
+		}
+	}
```
Comment (bartek977) [inline app/src/main/kotlin/com/intive/picover/validators/ValidationStatus.kt]: minor: instead of `when` you can use polymorphism ;)

**Review by bartek977 — APPROVED** [review]

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt (hunk 4 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: Done 😄

File: app/src/main/kotlin/com/intive/picover/validators/ValidationStatus.kt (hunk 5 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/validators/ValidationStatus.kt]: Done 😄

File: app/src/main/kotlin/com/intive/picover/validators/TextValidator.kt [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+import com.intive.picover.validators.ValidationStatus.ValidText
+
+class TextValidator private constructor(
+	private val text: String,
+	private val allowEmpty: Boolean?,
+	private val allowBlank: Boolean?,
+	private val maxLength: Int?,
+) {
+
+	fun validatingText(): ValidationStatus {
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/validators/TextValidator.kt:15]: minor: empty lines are not needed for the if's as well :)

**Review by marcinWisnia — APPROVED** [review]

File: app/src/main/kotlin/com/intive/picover/validators/TextValidator.kt (hunk 6 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/validators/TextValidator.kt:15]: Done 😄
