### PR TITLE
#121 Handle exception

### LINKED ISSUE #121: Profile screen
Requires authentication.

## Basic content:
- avatar
- username
- email

More features could be added up to the developer ideas.

## Future
In the future, this screen could be extended to include user activities such as:
- liked photos
- uploaded photos
- last comments
- bio

## Tasks: 

- [x] Show user data
- [x] Update avatar in Firebase
- [x] Adjust UI add information about edit for avatar
- [x] Update user name
- [x] Handle exception
- [x] Extract same statements from updateAvatar, updateName, fetchProfile in ProfileViewModel 
- [x] Add placeholder for loading
- [x] Validate text

### PR DESCRIPTION
**Pull request by Nataniel-Antosik**
<p align="center">
 
</p>

### CODE REVIEW

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt [hunk 1]
```diff
@@ -89,11 +92,18 @@ fun ProfileScreen(viewModel: ProfileViewModel) {
...
+			is Loaded -> {
+				ProfileSegment(profile.data(), photoLauncher, sheetState, coroutineScope)
+			}
+
+			is Loading -> {
+				CircularProgressIndicator()
+			}
+
+			is Error -> {
+				ErrorProfileSegment(viewModel::fetchProfile)
```
Comment (Nataniel-Antosik) [inline app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt]: @intive/android-guild-szczecin 
Or, if we would like I can go with our generic error placeholder:
<p align="center">
 
</p>

Comment (marcinWisnia) [reply app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt]: i think we could go with our generic error, same for loading and use properly modified PicoverLoader ?

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -20,4 +20,6 @@
     <string name="GenericErrorMessage">Something went wrong. Please try again later.</string>
     <string name="GenericErrorButtonText">Retry</string>
     <string name="EditUserData">Edit User Data</string>
+    <string name="ProfileError">Something went wrong \nClick to refresh</string>
+    <string name="ProfileErrorButtonRetry">Retry</string>
```
Comment (marcinWisnia) [inline app/src/main/res/values/strings.xml]: I think that we should avoid repeating this generic words. Let's imagine that we will have 10 screens and in every we will have a new word "Retry" added :D i would maybe go more with re-using the GenericErrorButtonText or change the string name for this to RetryButton or something like this :D to rethink :D

**Review by marcinWisnia — CHANGES_REQUESTED** [review]

File: app/src/main/res/values/strings.xml (hunk 2 above)
Comment (Nataniel-Antosik) [reply app/src/main/res/values/strings.xml]: Yes, I agree with you. I added this string because I thought about the situation when we would like to change something on one screen and don't want to make an impact on the other, but now I will go with the generic one to omit to repeat the same value 😄. Also, I will rename it to `RetryButton` to make the name more meaningful and easier to adjust in other places.

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt (hunk 1 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt]: Ok, I will go with a generic solution. What about the loader I have a special view for this in another PR because IMO it is a specific situation with the loader.

File: app/src/main/res/values/strings.xml (hunk 2 above)
Comment (Nataniel-Antosik) [reply app/src/main/res/values/strings.xml]: Done 😄

**Review by marcinWisnia — APPROVED** [review]

**Comment by kmaslowiec** [comment]
There are two commits:
image

**Review by BorysChajdas — APPROVED** [review]
