### PR TITLE
#121 Update user name

### LINKED ISSUE #121: Profile screen
Requires authentication.

## Basic content:
- avatar
- username
- email

More features could be added up to the developer ideas.

## Future
In the future, this screen could be extended to include user activities such as:
- liked photos
- uploaded photos
- last comments
- bio

## Tasks: 

- [x] Show user data
- [x] Update avatar in Firebase
- [x] Adjust UI add information about edit for avatar
- [x] Update user name
- [x] Handle exception
- [x] Extract same statements from updateAvatar, updateName, fetchProfile in ProfileViewModel 
- [x] Add placeholder for loading
- [x] Validate text

### PR DESCRIPTION
**Pull request by Nataniel-Antosik**
<p align="center">
 
</p>

### CODE REVIEW

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt [hunk 1]
```diff
@@ -60,6 +63,7 @@ class AuthRepositoryTest : ShouldSpec(
 
 		beforeSpec {
 			mockkStatic("kotlinx.coroutines.tasks.TasksKt")
+			mockkStatic(TextUtils::isEmpty, Uri::parse)
```
Comment (Nataniel-Antosik) [inline app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: Delete URI parse

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt [hunk 2]
```diff
@@ -112,29 +116,39 @@ class AuthRepositoryTest : ShouldSpec(
...
-				coEvery { await() } returns userPhoto
-			}
+			coEvery { referenceToUserAvatar.downloadUrl.await() } returns userPhoto
 
 			tested.userProfile() shouldBe profile
 		}
+
+		should("set display name WHEN updateUserName called") {
+			val slot = slot<UserProfileChangeRequest>()
+			val currentUser = mockk<FirebaseUser> {
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: please be consistent with declaring mocks :) we should declare them in one way, like val currentUser: FirebaseUser = mockk{
...
}

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt [hunk 3]
```diff
@@ -112,29 +116,39 @@ class AuthRepositoryTest : ShouldSpec(
...
+				every { email } returns userEmail
+			}
+			every { firebaseAuth.currentUser!! } returns currentUser
+			every { TextUtils.isEmpty(any()) } returns true
+			coEvery { currentUser.updateProfile(capture(slot)).await() } returns mockk()
+			coEvery { referenceToUserAvatar.downloadUrl.await() } returns userPhoto
+
+			tested.updateUserName("Marian Kowalski")
+
+			slot.captured.displayName!! shouldBeEqual "Marian Kowalski"
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt:152]: i think we should also check if user profile was returned, it can be in one test in my opinion.

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt [hunk 4]
```diff
@@ -45,17 +64,24 @@ import com.intive.picover.profile.model.Profile
...
+	val keyboardController = LocalSoftwareKeyboardController.current
 	var isDeleteAccountDialogVisible by remember { mutableStateOf(false) }
 	val photoLauncher = rememberLauncherForActivityResult(ActivityResultContracts.PickVisualMedia()) { uri ->
 		if (uri != null) {
 			viewModel.updateAvatar(uri)
 		}
 	}
+	val coroutineScope = rememberCoroutineScope()
+	val sheetState = rememberModalBottomSheetState()
+	var userName by remember { mutableStateOf("") }
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt:83]: alternatively, we could have userName in viewModel, which will be set from profile data name at the begining,  and use method updateUser with the value from viewmodel and avoid the launched effect, but this is just my thoughts, this is also ok for me as it is (the solution i've mentioned will probably give us possibility to test the originally set value, if was done properly )

**Review by marcinWisnia — CHANGES_REQUESTED** [review]

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt (hunk 4 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt:83]: Ok, I got your point, and to be honest I don't know if I would go with another variable. Do you know some disadvantages of the launched effect? 😄

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt (hunk 1 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: Done

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt (hunk 2 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: Done 😄

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt (hunk 3 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt:152]: Done 😄

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt (hunk 4 above)
Comment (marcinWisnia) [reply app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt:83]: i think that launched effect is not view-destroying aware :D but my main consideration was about testing the initially set value :)

Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt:83]: IMO done 😄

**Review by bartek977 — APPROVED** [review]

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt (hunk 2 above)
Comment (MarekMacko) [reply app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: Candidate to rule 😎

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt [hunk 5]
```diff
@@ -53,6 +55,21 @@ class ProfileViewModel @Inject constructor(
...
+	}
+
+	fun updateName(name: String) {
+		viewModelScope.launch {
+			_profile.value = Loading
+			runCatching {
+				authRepository.updateUserName(name)
+			}.onSuccess {
+				_profile.value = Loaded(it)
+				_userName.value = it.name
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: as we already discussed, please check later, is it possible to set user name automatically from updated profile value

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt [hunk 6]
```diff
@@ -80,5 +81,31 @@ class ProfileViewModelTest : ShouldSpec(
 
 			tested.profile.value shouldBe Loading
 		}
+
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt]: missing test for setting userName when fetching profile :) this can be added using assertSoftly for loaded test

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt [hunk 7]
```diff
@@ -80,5 +81,31 @@ class ProfileViewModelTest : ShouldSpec(
...
+		should("load profile WHEN updateName called") {
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt]: You should consider more dynamic way of testing the same actions for update/fetch profile :) maybe extracting `action`, such as tested.updateName or tested.fetchProfile  will do the job, especially when fetch profile will be also used for retry

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt (hunk 5 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: Done

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt (hunk 6 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt]: Done

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt (hunk 7 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt]: Done

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt [hunk 8]
```diff
@@ -45,17 +63,24 @@ import com.intive.picover.profile.model.Profile
...
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt:83]: do we need another userName now, as we have one in viewmodel ?

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt [hunk 9]
```diff
@@ -65,20 +71,62 @@ class ProfileViewModelTest : ShouldSpec(
 			coVerify { authRepository.updateUserAvatar(uri) }
 		}
 
-		should("load profile WHEN updateAvatar called") {
-			coEvery { authRepository.updateUserAvatar(uri) } returns profile
-
-			tested.updateAvatar(uri)
+		should("load profile WHEN updateAvatar/updateName called") {
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt]: the test name should be more generic, something like ..according to called method

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt (hunk 8 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt:83]: Now variable in VM is a state and we must probably have an extra userName on the UI to handle changing text. Maybe I don't see a way to have only one variable. 😄

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt (hunk 9 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt]: Done 😄

**Comment by MarekMacko** [comment]
@marcinWisnia Any update here?

File: app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt (hunk 4 above)
Comment (marcinWisnia) [reply app/src/main/kotlin/com/intive/picover/profile/view/ProfileScreen.kt:83]: Can't we just use userName from viewmodel and update this value, when we are doing "changes" on the textfield ? this was my desired solution :D

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt [hunk 10]
```diff
@@ -65,20 +71,62 @@ class ProfileViewModelTest : ShouldSpec(
...
+		}
 
-			tested.profile.value shouldBe Loaded(profile)
+		should("be loading WHEN specific method called and start executing") {
+			listOf(
+				ManageProfileParam(
+					{ authRepository.updateUserAvatar(uri) },
+					{ tested.updateAvatar(uri) },
+					Loading,
+				),
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt:98]: do we need loading here as we know that we will check loading in every test ? this could consist of two first values only

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt [hunk 11]
```diff
@@ -65,20 +71,62 @@ class ProfileViewModelTest : ShouldSpec(
...
-
-			tested.updateAvatar(uri)
+		should("load profile WHEN specific method called") {
+			listOf(
+				ManageProfileParam(
+					{ authRepository.updateUserAvatar(uri) },
+					{ tested.updateAvatar(uri) },
+					profile,
+				),
+				ManageProfileParam(
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt:80]: same here

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt [hunk 12]
```diff
@@ -70,6 +71,15 @@ class AuthRepository @Inject constructor(
...
+		requireUser().updateProfile(
+			userProfileChangeRequest {
+				displayName = userName
+			},
+		).await()
+		return userProfile()
+	}
+
 	private fun requireUser() =
 		firebaseAuth.currentUser!!
```
Comment (kmaslowiec) [inline app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt:84]: I think we should avoid double-bang operators (!!) as it might cause NullPointerException
Please see: https://firebase.google.com/docs/auth/android/manage-users#get_the_currently_signed-in_user

**Review by BorysChajdas — APPROVED** [review]

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt (hunk 11 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt:80]: Done

File: app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt (hunk 10 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModelTest.kt:98]: Yes, it is redundant I deleted it

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 12 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt:84]: I created an issue for this #170

**Review by marcinWisnia — APPROVED** [review]
