### PR TITLE
#121 Update avatar in Firebase

### LINKED ISSUE #121: Profile screen
Requires authentication.

## Basic content:
- avatar
- username
- email

More features could be added up to the developer ideas.

## Future
In the future, this screen could be extended to include user activities such as:
- liked photos
- uploaded photos
- last comments
- bio

## Tasks: 

- [x] Show user data
- [x] Update avatar in Firebase
- [x] Adjust UI add information about edit for avatar
- [x] Update user name
- [x] Handle exception
- [x] Extract same statements from updateAvatar, updateName, fetchProfile in ProfileViewModel 
- [x] Add placeholder for loading
- [x] Validate text

### PR DESCRIPTION
**Pull request by Nataniel-Antosik**

### CODE REVIEW

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt [hunk 1]
```diff
@@ -31,14 +38,17 @@ class AuthRepository @Inject constructor(
 		firebaseAuth.signOut()
 	}
 
-	fun userProfile() =
-		requireUser().let {
+	suspend fun userProfile(): Profile {
+		val reference = storageReference.child("user/${requireUser().uid}")
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: Maybe this whole user reference should be extracted to this val, as it is used few times ? (not only storage reference)

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt [hunk 2]
```diff
@@ -1,17 +1,24 @@
...
 import kotlinx.coroutines.flow.callbackFlow
 import kotlinx.coroutines.tasks.await
 
 class AuthRepository @Inject constructor(
+	firebaseStorage: FirebaseStorage,
 	private val firebaseAuth: FirebaseAuth,
+	private val bitmapConverter: BitmapConverter,
 ) {
 
+	private val storageReference = firebaseStorage.reference
```
Comment (BorysChajdas) [inline app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: Why not inject it directly?

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 1 above)
Comment (BorysChajdas) [inline app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: It is repeated two times, maybe extract it?

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt [hunk 3]
```diff
@@ -47,6 +57,11 @@ class AuthRepository @Inject constructor(
 			.await()
 	}
 
+	suspend fun updateUserAvatar(uri: Uri) {
+		val reference = storageReference.child("user/${requireUser().uid}")
+		reference.putBytes(bitmapConverter.convertBitmapToBytes(uri, 50).toByteArray()).await()
```
Comment (BorysChajdas) [inline app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: `50` should be extracted or a named parameter should be used. Maybe even better would be to just use `50` as a default value in `BitmapConverter` to not pass it as a parameter.

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt [hunk 4]
```diff
@@ -68,12 +84,44 @@ class AuthRepositoryTest : ShouldSpec(
...
+				every { isCanceled } returns false
+				every { result } returns mockk()
+			}
+
+			tested.updateUserAvatar(userPhoto)
+
+			verify { bitmapConverter.convertBitmapToBytes(userPhoto, quality) }
+		}
+
+		should("call StorageReference.putBytes WHEN updateUserAvatar called") {
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt:114]: I would arrange this tests in a different way: One test, instead of two, in which we check:
- if the storageReference.putBytes was called with specific value, this can be a mock, which is returned from bitmapConverter.convertBitmapToBytes when userPhoto and quality is passed there

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt [hunk 5]
```diff
@@ -15,16 +19,28 @@ import io.mockk.mockkStatic
...
+		val firebaseAuth: FirebaseAuth = mockk(relaxUnitFun = true)
+		val storageReference: StorageReference = mockk()
+		val bitmapConverter = mockk<BitmapConverter> {
+			every { convertBitmapToBytes(any(), any()) } returns byteArrayOutputStream
+		}
+		val firebaseStorage: FirebaseStorage = mockk(relaxed = true) {
+			every { reference.child("user/$userUid") } returns storageReference
+		}
+		val tested = AuthRepository(firebaseStorage, firebaseAuth, bitmapConverter)
+		isolationMode = IsolationMode.InstancePerTest
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: i think we agreed on that test setup is on the beginning of the file, please check other tests

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt [hunk 6]
```diff
@@ -35,7 +36,17 @@ class ProfileViewModel @Inject constructor(
 		}
 	}
 
+	fun updateAvatar(uri: Uri) {
+		viewModelScope.launch {
+			_profile.value = Loading
+			authRepository.updateUserAvatar(uri)
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: what if this request fail ?

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt [hunk 7]
```diff
@@ -35,7 +36,17 @@ class ProfileViewModel @Inject constructor(
...
+			fetchProfile()
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: Aren't we loosing Loading state now, if the update is finished ?

Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: same situation like in Your bench project :D

**Review by marcinWisnia — CHANGES_REQUESTED** [review]

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 1 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: Yes, now I only used it to make reference to the specific user photo so I can create one variable for this case.

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt (hunk 5 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: Yes, a configuration in other places is at the beginning of the test. I will change it.

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt (hunk 7 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: What do you mean? I set the profile in the loading state to show the progress bar and when the avatar will be updating and it will finish correctly. We run fetchProfile() to refresh data.

Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: Yes, the same situation mabey I can find a solution here 😄

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 1 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: Done 😄

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt (hunk 4 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt:114]: Done 😄

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt (hunk 5 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: Done 😄

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt (hunk 6 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: Now I didn't handle it. I can add it in the near PR for this task

**Review by BorysChajdas — CHANGES_REQUESTED** [review]

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt [hunk 8]
```diff
@@ -35,7 +36,17 @@ class ProfileViewModel @Inject constructor(
...
+		}
+	}
+
 	private fun fetchProfile() {
-		_profile.value = Loaded(authRepository.userProfile())
+		viewModelScope.launch {
+			_profile.value = Loaded(authRepository.userProfile())
```
Comment (bartek977) [inline app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: you can use `runCatching` block and add TODO in case on fail, something like this:

```
runCatching { authRepository.userProfile() }
            .onSuccess { _profile.value = Loaded(it) }
            .onFailure { // TODO to be done }
```

then it's clear you didn't forget about error handling and it will be done later

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 1 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: I don't know why but you added a comment to outdated code :P

Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: I changed it after this comment https://github.com/intive/Picover/pull/152#discussion_r1273354218

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 2 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: When I tried to inject it directly I got this exception 
```
09:30:44.123  E  StorageException has occurred.
                 User does not have permission to access this object.
                  Code: -13021 HttpResult: 403
09:30:44.124  E  {  "error": {    "code": 403,    "message": "Permission denied."  }}
                 java.io.IOException: {  "error": {    "code": 403,    "message": "Permission denied."  }}
                 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:445)
                 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:462)
                 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:453)
                 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
                 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:289)
                 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:76)
                 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:68)
                 	at com.google.firebase.storage.GetDownloadUrlTask.run(GetDownloadUrlTask.java:77)
```
maybe we can try to change it in the near future. I will go with an old way with injected `FirebaseStorage`

Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: Ok, nvm I found the reason for the problem and now I can inject it directly 😅

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 3 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: I will go with the default value in `BitmapConverter`

Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: Done 😄

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 2 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: Done 😄

File: app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt (hunk 8 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: Thanks for advice 😄

Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt]: Done 😄

File: app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt [hunk 9]
```diff
@@ -81,12 +111,27 @@ class AuthRepositoryTest : ShouldSpec(
...
+			every { referenceToUserAvatar.downloadUrl } returns mockk {
+				coEvery { await() } returns userPhoto
+			}
+
+			tested.updateUserAvatar(userPhoto)
+
+			verify { referenceToUserAvatar.putBytes(byteArrayOutputStream.toByteArray()) }
+		}
+
+		should("call StorageReference.putBytes WHEN updateUserAvatar called2") {
```
Comment (marcinWisnia) [inline app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: called2 :D ?

Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: Yes, I forgot to change it 🙃

Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt]: Done 😄

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt [hunk 10]
```diff
@@ -1,19 +1,26 @@
...
 import kotlinx.coroutines.flow.callbackFlow
 import kotlinx.coroutines.tasks.await
 
 class AuthRepository @Inject constructor(
+	storageReference: StorageReference,
 	private val firebaseAuth: FirebaseAuth,
+	private val bitmapConverter: BitmapConverter,
 ) {
 
+	private val storageReferenceToUserAvatar = storageReference.child("user/${requireUser().uid}")
```
Comment (BorysChajdas) [inline app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: Or just `userAvatarStorageReference`/`userAvatarReference`

File: app/src/main/kotlin/com/intive/picover/common/converters/BitmapConverter.kt [hunk 11]
```diff
@@ -0,0 +1,30 @@
...
+import com.intive.picover.common.sdk.AndroidSdkVersion
+import dagger.hilt.android.qualifiers.ApplicationContext
+import java.io.ByteArrayOutputStream
+import javax.inject.Inject
+
+class BitmapConverter @Inject constructor(
+	@ApplicationContext private val context: Context,
+) {
+
+	fun convertBitmapToBytes(uri: Uri, quality: Int = 50): ByteArrayOutputStream {
```
Comment (BorysChajdas) [inline app/src/main/kotlin/com/intive/picover/common/converters/BitmapConverter.kt]: The `quality` parameter is a percent of quality? If so it would be better to name it `qualityPercent`

File: app/src/main/kotlin/com/intive/picover/common/di/AppModule.kt [hunk 12]
```diff
@@ -13,9 +13,13 @@ import kotlinx.coroutines.Dispatchers
 @InstallIn(SingletonComponent::class)
 object AppModule {
 
+	// TODO replace it using a new provider to the storage reference
```
Comment (BorysChajdas) [inline app/src/main/kotlin/com/intive/picover/common/di/AppModule.kt]: You will take care of this TODO? If so then add your acronym to TODO. For me this TODO is not clear what should be changed :D

**Review by BorysChajdas — CHANGES_REQUESTED** [review]

File: app/src/main/kotlin/com/intive/picover/common/converters/BitmapConverter.kt (hunk 11 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/common/converters/BitmapConverter.kt]: Probably it is in the percent 
image

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 10 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: I will go with `userAvatarReference` :)

File: app/src/main/kotlin/com/intive/picover/common/converters/BitmapConverter.kt (hunk 11 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/common/converters/BitmapConverter.kt]: I will change it to the `qualityPercent` :D

File: app/src/main/kotlin/com/intive/picover/common/di/AppModule.kt (hunk 12 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/common/di/AppModule.kt]: Yes, I will fix this and I will add an acronym in TODO :D

File: app/src/test/kotlin/com/intive/picover/common/converters/BitmapConverterTest.kt [hunk 13]
```diff
@@ -0,0 +1,66 @@
...
+import com.intive.picover.common.sdk.AndroidSdkVersion
+import io.kotest.core.spec.style.ShouldSpec
+import io.mockk.every
+import io.mockk.mockk
+import io.mockk.mockkObject
+import io.mockk.mockkStatic
+import io.mockk.unmockkAll
+import io.mockk.verify
+
+class BitmapConverterTest : ShouldSpec(
```
Comment (BorysChajdas) [inline app/src/test/kotlin/com/intive/picover/common/converters/BitmapConverterTest.kt:21]: None of the tests is checking the value returned after calling `convertBitmapToBytes`

File: app/src/main/kotlin/com/intive/picover/common/di/AppModule.kt (hunk 12 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/common/di/AppModule.kt]: Also, I will try to clarify this comment :P

**Review by BorysChajdas — CHANGES_REQUESTED** [review]

File: app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt (hunk 10 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt]: Done :D

File: app/src/main/kotlin/com/intive/picover/common/converters/BitmapConverter.kt (hunk 11 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/common/converters/BitmapConverter.kt]: Done :D

File: app/src/main/kotlin/com/intive/picover/common/di/AppModule.kt (hunk 12 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/common/di/AppModule.kt]: Done :D

File: app/src/test/kotlin/com/intive/picover/common/converters/BitmapConverterTest.kt (hunk 13 above)
Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/common/converters/BitmapConverterTest.kt:21]: Yes, you have a point I should add this test

Comment (Nataniel-Antosik) [reply app/src/test/kotlin/com/intive/picover/common/converters/BitmapConverterTest.kt:21]: Done 😄

**Review by BorysChajdas — APPROVED** [review]

File: app/src/main/kotlin/com/intive/picover/common/sdk/AndroidSdkVersion.kt [hunk 14]
```diff
@@ -0,0 +1,8 @@
+package com.intive.picover.common.sdk
+
+import android.os.Build
+
+object AndroidSdkVersion {
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/common/sdk/AndroidSdkVersion.kt:5]: Minor: please add empty line

**Review by marcinWisnia — APPROVED** [review]

File: app/src/main/kotlin/com/intive/picover/common/sdk/AndroidSdkVersion.kt (hunk 14 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/common/sdk/AndroidSdkVersion.kt:5]: Done 😄
