### PR TITLE
#121 Add placeholder for loading

### LINKED ISSUE #121: Profile screen
Requires authentication.

## Basic content:
- avatar
- username
- email

More features could be added up to the developer ideas.

## Future
In the future, this screen could be extended to include user activities such as:
- liked photos
- uploaded photos
- last comments
- bio

## Tasks: 

- [x] Show user data
- [x] Update avatar in Firebase
- [x] Adjust UI add information about edit for avatar
- [x] Update user name
- [x] Handle exception
- [x] Extract same statements from updateAvatar, updateName, fetchProfile in ProfileViewModel 
- [x] Add placeholder for loading
- [x] Validate text

### PR DESCRIPTION
**Pull request by Nataniel-Antosik**
## [Source](https://medium.com/@m.derakhshan/how-to-implement-the-shimmer-effect-using-jetpack-compose-fc0e81e47747) of animation

These changes are to avoid UI jumping during the loading/updating of profile data.

### Loading placeholder:
<p align="center">
 
</p>

### CODE REVIEW

File: app/src/main/kotlin/com/intive/picover/common/animations/ShimmerBrush.kt [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+import androidx.compose.animation.core.infiniteRepeatable
+import androidx.compose.animation.core.rememberInfiniteTransition
+import androidx.compose.animation.core.tween
+import androidx.compose.runtime.Composable
+import androidx.compose.ui.geometry.Offset
+import androidx.compose.ui.graphics.Brush
+import androidx.compose.ui.graphics.Color
+
+@Composable
+fun ShimmerBrush(
```
Comment (marcinWisnia) [inline app/src/main/kotlin/com/intive/picover/common/animations/ShimmerBrush.kt:14]: Rihanna - Diamonds

**Review by marcinWisnia — APPROVED** [review]

File: app/src/main/kotlin/com/intive/picover/common/animations/ShimmerBrush.kt [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+	targetValue: Float = 1000f,
+): Brush {
+	return if (showShimmer) {
+		val shimmerColors = listOf(
+			Color.LightGray.copy(alpha = 0.6f),
+			Color.LightGray.copy(alpha = 0.2f),
+			Color.LightGray.copy(alpha = 0.6f),
+		)
+
+		val transition = rememberInfiniteTransition(label = "")
```
Comment (BorysChajdas) [inline app/src/main/kotlin/com/intive/picover/common/animations/ShimmerBrush.kt]: Would be better to add real label instead of empty string :D

**Review by BorysChajdas — APPROVED** [review]

File: app/src/main/kotlin/com/intive/picover/common/animations/ShimmerBrush.kt (hunk 2 above)
Comment (Nataniel-Antosik) [reply app/src/main/kotlin/com/intive/picover/common/animations/ShimmerBrush.kt]: Done 😄
